language: java
jdk: 
  - oraclejdk8
  - oraclejdk7
# This is a comment
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
